project:
  type: website
  output-dir: docs

website:
  title: "Stuart B. Moore"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: resources/sbm-cv.pdf
        text: CV
      - href: posts.qmd
        text: Posts
    right:
      - icon: github
        href: https://github.com/s-b-moore
      - icon: bluesky
        href: https://bsky.app/profile/sbmoore.bsky.social
  open-graph: true
  twitter-card: true

format:
  html:
    page-layout: full
    theme:
      - journal
    css: styles.css
    toc: true
